/****** Script for SelectTopNRows command from SSMS  ******/
SELECT TOP (1000) [user_id]
      ,[patient_name]
      ,[email]
      ,[mobile]
      ,[gender]
      ,[age]
      ,[date]
      ,[time]
      ,[address]
  FROM [AppointmentDB].[dbo].[Patient_Details]